# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# You can specify a custom docker image from Docker Hub as your build environment.

image: python:3.7.3

pipelines:
  default:
    - step:
        script:
          - conda config --append channels conda-forge
          - conda config --append channels cmutel
          - conda config --append channels haasad
          - pip install -r requirements.txt
          - pip install swolfpy 
