# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# You can specify a custom docker image from Docker Hub as your build environment.

image: python:3.7.3

pipelines:
  default:
    - step:
        script:
          - pip install -y -q -c conda-forge -c cmutel -c haasad brightway2 jupyter
          - pip install -r requirements.txt
          - pip install https://bitbucket.org/swolfpy/swolfpy_inputdata/get/master.zip
          - pip install https://bitbucket.org/swolfpy/swolfpy_processmodels/get/master.zip
          - pip install https://bitbucket.org/swolfpy/swolfpy/get/master.zip
          - pytest



