name: base
channels:
  - defaults
  - conda-forge
  - cmutel
  - haasad
dependencies:
  - pip
  - pip:
    - brightway2==2.3.0
    - graphviz
    - xlrd==1.2.0
    - PySide2==5.14.0
    - plotly
    - pandas
    - pyDOE
    - jupyter
    - pytest
    - pytest-cov
    - pytest-flake8
