name: base
channels:
  - defaults
  - conda-forge
  - cmutel
  - haasad
dependencies:
  - pip
  - pip:
    - brightway2==2.3.0
    - coverage
    - graphviz
    - numpy==1.24.*
    - pandas==2.0.*
    - plotly
    - pyDOE
    - PySide2==5.15.*
    - pytest
    - pytest-cov
    - pytest-flake8
    - scipy==1.8.0
    - xlrd==1.2.0
