name: base
channels:
  - defaults
  - conda-forge
  - cmutel
  - haasad
dependencies:
  - pip
  - pip:
    - brightway2==2.3
    - bw-migrations==0.1
    - bw2analyzer==0.10
    - bw2calc==1.8.2
    - bw2data==3.6.5
    - bw2io==0.8.8
    - bw2parameters==1.1.0
    - coverage
    - graphviz
    - plotly
    - pyDOE
    - PySide2==5.15.*
    - pytest
    - pytest-cov
    - pytest-flake8
    - scipy==1.8.0
    - xlrd==1.2.0
