name: base
channels:
  - defaults
  - conda-forge
  - cmutel
  - haasad
dependencies:
  - pip
  - pip:
    - brightway2==2.3
    - bw-migrations==0.1
    - bw2analyzer==0.9.4
    - bw2calc==1.8.0
    - bw2data==3.6.6
    - bw2io==0.7.12.1
    - bw2parameters==0.6.6
    - coverage
    - graphviz
    - numpy==1.24.*
    - pandas==2.0.*
    - plotly
    - pyDOE
    - PySide2==5.15.*
    - pytest
    - pytest-cov
    - pytest-flake8
    - scipy==1.8.0
    - xlrd==1.2.0
