name: swolfpy
channels:
  - defaults
  - conda-forge
  - cmutel
  - haasad
dependencies:
  - python=3.7
  - brightway2
  - pip
  - pip:
    - graphviz
    - xlrd
    - PySide2
    - plotly
    - pandas
    - jupyter

