# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MC.ui',
# licensing of 'MC.ui' applies.
#
# Created: Tue Oct 20 00:31:36 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MC_Results(object):
    def setupUi(self, MC_Results):
        MC_Results.setObjectName("MC_Results")
        MC_Results.resize(1180, 1068)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ICONS/PySWOLF_ICONS/PySWOLF.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MC_Results.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(MC_Results)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(MC_Results)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.MC_Data = QtWidgets.QWidget()
        self.MC_Data.setObjectName("MC_Data")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MC_Data)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MC_Res_Table = QtWidgets.QTableView(self.MC_Data)
        self.MC_Res_Table.setObjectName("MC_Res_Table")
        self.gridLayout_2.addWidget(self.MC_Res_Table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.MC_Data, "")
        self.MC_Plot = QtWidgets.QWidget()
        self.MC_Plot.setObjectName("MC_Plot")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.MC_Plot)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.MC_Plot)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1136, 998))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter = QtWidgets.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setMinimumSize(QtCore.QSize(0, 900))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.splitter_2 = QtWidgets.QSplitter(self.frame)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 1)
        self.hexbin = QtWidgets.QRadioButton(self.groupBox)
        self.hexbin.setObjectName("hexbin")
        self.gridLayout_3.addWidget(self.hexbin, 1, 5, 1, 1)
        self.y_axis = QtWidgets.QComboBox(self.groupBox)
        self.y_axis.setMinimumSize(QtCore.QSize(400, 0))
        self.y_axis.setObjectName("y_axis")
        self.gridLayout_3.addWidget(self.y_axis, 1, 1, 1, 1)
        self.scatter = QtWidgets.QRadioButton(self.groupBox)
        self.scatter.setObjectName("scatter")
        self.gridLayout_3.addWidget(self.scatter, 1, 4, 1, 1)
        self.x_axis = QtWidgets.QComboBox(self.groupBox)
        self.x_axis.setObjectName("x_axis")
        self.gridLayout_3.addWidget(self.x_axis, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.Update_plot = QtWidgets.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ICONS/PySWOLF_ICONS/Update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Update_plot.setIcon(icon1)
        self.Update_plot.setObjectName("Update_plot")
        self.gridLayout_3.addWidget(self.Update_plot, 1, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 7, 1, 1)
        self.plot = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.plot.setSizePolicy(sizePolicy)
        self.plot.setMinimumSize(QtCore.QSize(0, 100))
        self.plot.setObjectName("plot")
        self.gridLayout_3.addWidget(self.plot, 2, 0, 1, 8)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 2, 1)
        self.plot_dist = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_dist.sizePolicy().hasHeightForWidth())
        self.plot_dist.setSizePolicy(sizePolicy)
        self.plot_dist.setMinimumSize(QtCore.QSize(0, 100))
        self.plot_dist.setObjectName("plot_dist")
        self.gridLayout_4.addWidget(self.plot_dist, 3, 0, 1, 6)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.param = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.param.sizePolicy().hasHeightForWidth())
        self.param.setSizePolicy(sizePolicy)
        self.param.setMinimumSize(QtCore.QSize(400, 0))
        self.param.setObjectName("param")
        self.gridLayout_4.addWidget(self.param, 0, 1, 1, 3)
        self.hist = QtWidgets.QRadioButton(self.groupBox_2)
        self.hist.setObjectName("hist")
        self.gridLayout_4.addWidget(self.hist, 2, 1, 1, 1)
        self.box = QtWidgets.QRadioButton(self.groupBox_2)
        self.box.setObjectName("box")
        self.gridLayout_4.addWidget(self.box, 2, 2, 1, 1)
        self.density = QtWidgets.QRadioButton(self.groupBox_2)
        self.density.setObjectName("density")
        self.gridLayout_4.addWidget(self.density, 2, 3, 1, 1)
        self.Update_dist_fig = QtWidgets.QPushButton(self.groupBox_2)
        self.Update_dist_fig.setIcon(icon1)
        self.Update_dist_fig.setObjectName("Update_dist_fig")
        self.gridLayout_4.addWidget(self.Update_dist_fig, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 5, 1, 1)
        self.gridLayout_7.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.splitter, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.MC_Plot, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(MC_Results)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MC_Results)

    def retranslateUi(self, MC_Results):
        MC_Results.setWindowTitle(QtWidgets.QApplication.translate("MC_Results", "Monte Carlo Results", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MC_Data), QtWidgets.QApplication.translate("MC_Results", "Data", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MC_Results", "Plot", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MC_Results", "Plot type", None, -1))
        self.hexbin.setText(QtWidgets.QApplication.translate("MC_Results", "hexbin", None, -1))
        self.scatter.setText(QtWidgets.QApplication.translate("MC_Results", "scatter", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MC_Results", "X axis", None, -1))
        self.Update_plot.setText(QtWidgets.QApplication.translate("MC_Results", "Update", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MC_Results", "Y axis", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MC_Results", "Distribution", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MC_Results", "Plot type", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MC_Results", "Parameter", None, -1))
        self.hist.setText(QtWidgets.QApplication.translate("MC_Results", "hist", None, -1))
        self.box.setText(QtWidgets.QApplication.translate("MC_Results", "box", None, -1))
        self.density.setText(QtWidgets.QApplication.translate("MC_Results", "density", None, -1))
        self.Update_dist_fig.setText(QtWidgets.QApplication.translate("MC_Results", "Update", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MC_Plot), QtWidgets.QApplication.translate("MC_Results", "Plot", None, -1))

from . import PyWOLF_Resource_rc
